### ISSUE TITLE
Flutter 3.0.0 Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by ivirtex** [koukibadr/Elegant-Notification#60] opened 2022-05-15 15:23 UTC
Since Flutter 3.0.0, there is a warning in the debug console:
```
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/lib/elegant_notification.dart:430
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addPostFrameCallback((_) {
```

Should be an easy fix at `lib/elegant_notification.dart:430`

**Comment by koukibadr** [comment] 2022-05-17 05:26
Thanks @ivirtex  for filling this issue we will work on it

**Comment by koukibadr** [comment] 2022-05-25 21:21
@ivirtex the issue is fixed once I publish a new version I will let you know

**Comment by koukibadr** [comment] 2022-05-30 21:30
@ivirtex I just published the version that fixes this bug

**Comment by ivirtex** [comment] 2022-05-31 15:20
Thanks!

**Closed** 2022-06-07 18:16 UTC
Labels: bug
